server:
  port: 6003
  
spring:
  application:
    name: client-service2
    
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      {"defaultZone":"http://localhost:6001/eureka/"}