server:
  port: 6003
  
spring:
  rabbitmq:
    host: 192.168.0.106
    port: 5672
    username: guest
    password: guest 
  application:
    name: client-service2
    
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      {"defaultZone":"http://localhost:6001/eureka/"}