server:
  port: 6002
  
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      {"defaultZone":"http://localhost:6001/eureka/"}
      
spring:
  application:
    name: client-service1